package com.xuanfeng.weather.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APP_KV".
 */
public class AppKv {

    private Long id;
    /** Not-null value. */
    private String appKey;
    private String appVal;

    public AppKv() {
    }

    public AppKv(Long id) {
        this.id = id;
    }

    public AppKv(Long id, String appKey, String appVal) {
        this.id = id;
        this.appKey = appKey;
        this.appVal = appVal;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getAppKey() {
        return appKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    public String getAppVal() {
        return appVal;
    }

    public void setAppVal(String appVal) {
        this.appVal = appVal;
    }

}
