package com.xuanfeng.weather.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appKvDaoConfig;

    private final AppKvDao appKvDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appKvDaoConfig = daoConfigMap.get(AppKvDao.class).clone();
        appKvDaoConfig.initIdentityScope(type);

        appKvDao = new AppKvDao(appKvDaoConfig, this);

        registerDao(AppKv.class, appKvDao);
    }
    
    public void clear() {
        appKvDaoConfig.getIdentityScope().clear();
    }

    public AppKvDao getAppKvDao() {
        return appKvDao;
    }

}
